In [122]:
import pandas as pd
pd.set_option("display.width", 200)

In [123]:
##############
# Import CSV
##############
df = pd.read_csv("../data/netflix_titles.csv")
test = pd.read_csv("../data/netflix_titles.csv")
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB
None

In [124]:
############
# Extracting important data
############

netflix_df = df[["show_id", "type", "title" ,"country", "date_added", "release_year", "rating", "duration", "listed_in"]]
netflix_df.head(15)

,show_id,type,title,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."
5,s6,TV Show,Midnight Mass,NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
6,s7,Movie,My Little Pony: A New Generation,NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies
7,s8,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
8,s9,TV Show,The Great British Baking Show,United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV"
9,s10,Movie,The Starling,United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas"
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S..."
11,s12,TV Show,Bangkok Breaking,NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
12,s13,Movie,Je Suis Karl,"Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies"
13,s14,Movie,Confessions of an Invisible Girl,NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies"
14,s15,TV Show,Crime Stories: India Detectives,NaN,"September 22, 2021",2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries"

In [125]:
###########
# Amount of nulls in each column
###########
netflix_df.isna().sum().sort_values(ascending=False)

country         831
date_added       10
rating            4
duration          3
show_id           0
type              0
title             0
release_year      0
listed_in         0
dtype: int64

In [126]:
###########
# Cleaning country column
###########
netflix_df["country"] = netflix_df["country"].fillna("Unknown")
print(netflix_df["country"])

0       United States
1        South Africa
2             Unknown
3             Unknown
4               India
            ...
8802    United States
8803          Unknown
8804    United States
8805    United States
8806            India
Name: country, Length: 8807, dtype: str

In [127]:
###########
# Moving values from the rating to the duration columns
###########
dirty_rating = netflix_df["rating"].str.contains("min", na=False)

netflix_df.loc[dirty_rating, "duration"] = netflix_df.loc[dirty_rating, "rating"]

netflix_df.loc[dirty_rating, "rating"] = pd.NA

###########
# Extract numeric values from the duration column and changing type to int
###########

netflix_df["duration"] = netflix_df["duration"].str.extract(r"(\d+)")

netflix_df["duration"] = netflix_df["duration"].astype("Int64")

In [128]:
###########
# Cleaning rating column
###########
netflix_df["rating"] = netflix_df["rating"].fillna("Unrated")

In [ ]:
###########
# Trimming column date_added and changing data type to datetime
###########
netflix_df["date_added"] = netflix_df["date_added"].str.strip()

netflix_df["date_added"] = pd.to_datetime(netflix_df["date_added"], format="%B %d, %Y", errors="coerce")

In [ ]:
netflix_df.head(15)

,show_id,type,title,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,United States,2021-09-25,2020,PG-13,90,Documentaries
1,s2,TV Show,Blood & Water,South Africa,2021-09-24,2021,TV-MA,2,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Unknown,2021-09-24,2021,TV-MA,1,"Crime TV Shows, International TV Shows, TV Act..."
3,s4,TV Show,Jailbirds New Orleans,Unknown,2021-09-24,2021,TV-MA,1,"Docuseries, Reality TV"
4,s5,TV Show,Kota Factory,India,2021-09-24,2021,TV-MA,2,"International TV Shows, Romantic TV Shows, TV ..."
5,s6,TV Show,Midnight Mass,Unknown,2021-09-24,2021,TV-MA,1,"TV Dramas, TV Horror, TV Mysteries"
6,s7,Movie,My Little Pony: A New Generation,Unknown,2021-09-24,2021,PG,91,Children & Family Movies
7,s8,Movie,Sankofa,"United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125,"Dramas, Independent Movies, International Movies"
8,s9,TV Show,The Great British Baking Show,United Kingdom,2021-09-24,2021,TV-14,9,"British TV Shows, Reality TV"
9,s10,Movie,The Starling,United States,2021-09-24,2021,PG-13,104,"Comedies, Dramas"
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",Unknown,2021-09-24,2021,TV-MA,1,"Crime TV Shows, Docuseries, International TV S..."
11,s12,TV Show,Bangkok Breaking,Unknown,2021-09-23,2021,TV-MA,1,"Crime TV Shows, International TV Shows, TV Act..."
12,s13,Movie,Je Suis Karl,"Germany, Czech Republic",2021-09-23,2021,TV-MA,127,"Dramas, International Movies"
13,s14,Movie,Confessions of an Invisible Girl,Unknown,2021-09-22,2021,TV-PG,91,"Children & Family Movies, Comedies"
14,s15,TV Show,Crime Stories: India Detectives,Unknown,2021-09-22,2021,TV-MA,1,"British TV Shows, Crime TV Shows, Docuseries"